from flask import Blueprint, request

# Custom modules
# from app.lib.dataset import NetCDFExtractor, NetCDFRetriever
from app.lib.energy import get_estimated_energy
from app.utils.validators import get_or_none
# from app.utils.dates import get_current_year
from app.utils.sdl_predictor import calculate_SDL

# Custom Responses
from app.utils.responses import APIBaseException, BadRequestException, Success

"""
The APIs for accessing data portal
"""
data_bp = Blueprint("data", __name__)


@data_bp.route("/sdlr", methods=["POST"])
def get_sdlr():
    """
    Returns the SDLR for the given lat, lon
    """
    json = request.get_json()

    # Get the required values
    date = get_or_none(json, "date")
    lat = get_or_none(json, "lat")
    lon = get_or_none(json, "lon")

    # Validate the input
    if date is None or lat is None or lon is None:
        return BadRequestException(
            msg="Invalid date format", payload={"date": date}
        ).response

   
    sdlr_data = calculate_SDL(lat, lon, date)
    
    return Success(
        msg="found SDLR data", 
        payload={"sdlr": sdlr_data}
    ).response


@data_bp.route("/energy", methods=["POST"])
def get_energy():
    """
    Returns the energy generated by the panel in that time
    """
    json = request.get_json()

    # Get the required values
    month = get_or_none(json, "month")
    lat = get_or_none(json, "lat")
    lon = get_or_none(json, "lon")
    area = get_or_none(json, "area")
    efficiency = get_or_none(json, "efficiency")

    try:
        energy, total = get_estimated_energy(lat, lon, area, efficiency, month)
    except Exception as e:
        return APIBaseException(
            msg="Internal Server error", code=500, payload={"error": str(e)}
        ).response

    return Success(
        msg="energy for the year", payload={"months": energy, "total": total}
    ).response
